### ISSUE TITLE
Contribuição

### ISSUE THREAD

**Issue by MatheusMoura17** [acessibilidade/magoo#1]
@msales78 o projeto ainda está de pé? Gostaria de saber mais informações, a proposta é fazer um construtor de sites ou algo do tipo?

**Comment by msales78** [comment]
Olá @MatheusMoura17 sim, o projeto está de pé sim! Está atrasado, mas está de pé... a proposta é disponibilizar uma biblioteca de elementos para construção. Em um primeiro momento uma versão dos elementos em Adobe XD prontos para prototipação e em um segundo momento os elementos codificados e prontos para uso.

**Comment by MatheusMoura17** [comment]
Poxa, que massa!

Estava buscando por construtores de sites que priorizem acessibilidade, mas não encontrei nenhum que ofereça o mínimo possível (o máximo que encontrei foi adicionar alt nas imagens, criar âncoras e coisas mais básicas).

Foi ai que encontrei o ilustre [GrapeJs](https://github.com/artf/grapesjs), parece ser uma mão na roda pra construir uma interface entre _"arte"_ e _"código"_. Mas não oferece muitos recursos de acessibilidade... Mas por ser open source, acho que pode ajudar a dar um gás no Magoo.

Fiquei super empolgado com o projeto Magoo, se eu puder contribuir de alguma forma, me deixo a disposição.

**Comment by GustavoCruz** [comment]
Olá Marcelo Sales, o seu projeto é muito interessante. Acredito que irá beneficiar muitas pessoas.
Sou designer e também estou trabalhando com desenvolvimento de Design System e queria saber se é possível colaborar com o seu projeto.

**Comment by msales78** [comment]
Olá @GustavoCruz valeu pelo interesse... o projeto está em stand-by, pois pretendo pensar em novas formas de criação do mesmo... mas em breve teremos novidades por aqui... :)

abs
